// Code generated by "stringer -type Status,LatencyReq,DeviceState -output const_strings.go"; DO NOT EDIT.

package znp

import "strconv"

const (
	_Status_name_0 = "SuccessFailureInvalidParameter"
	_Status_name_1 = "ItemCreatedAndInitializedInitializationFailed"
	_Status_name_2 = "BadLength"
	_Status_name_3 = "MemErrorBufferFullUnsupportedModeMacMemError"
	_Status_name_4 = "SapiInProgressSapiTimeoutSapiInit"
	_Status_name_5 = "OtaAbortOtaImageInvalidOtaWaitForDataOtaNoImageAvailableOtaRequireMoreImage"
	_Status_name_6 = "SecNoKeySecOldFrmCountSecMaxFrmCountSecCcmFail"
	_Status_name_7 = "ApsFailApsTableFullApsIllegalRequestApsInvalidBindingApsUnsupportedAttribApsNotSupportedApsNoAckApsDuplicateEntryApsNoBoundDeviceApsNotAllowedApsNotAuthenticated"
	_Status_name_8 = "NwkInvalidParamNwkInvalidRequestNwkNotPermittedNwkStartupFailureNwkAlreadyPresentNwkSyncFailureNwkTableFullNwkUnknownDeviceNwkUnsupportedAttributeNwkNoNetworksNwkLeaveUnconfirmedNwkNoAckNwkNoRoute"
)

var (
	_Status_index_0 = [...]uint8{0, 7, 14, 30}
	_Status_index_1 = [...]uint8{0, 25, 45}
	_Status_index_3 = [...]uint8{0, 8, 18, 33, 44}
	_Status_index_4 = [...]uint8{0, 14, 25, 33}
	_Status_index_5 = [...]uint8{0, 8, 23, 37, 56, 75}
	_Status_index_6 = [...]uint8{0, 8, 22, 36, 46}
	_Status_index_7 = [...]uint8{0, 7, 19, 36, 53, 73, 88, 96, 113, 129, 142, 161}
	_Status_index_8 = [...]uint8{0, 15, 32, 47, 64, 81, 95, 107, 123, 146, 159, 178, 186, 196}
)

func (i Status) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _Status_name_0[_Status_index_0[i]:_Status_index_0[i+1]]
	case 12 <= i && i <= 13:
		i -= 12
		return _Status_name_1[_Status_index_1[i]:_Status_index_1[i+1]]
	case i == 17:
		return _Status_name_2
	case 22 <= i && i <= 25:
		i -= 22
		return _Status_name_3[_Status_index_3[i]:_Status_index_3[i+1]]
	case 42 <= i && i <= 44:
		i -= 42
		return _Status_name_4[_Status_index_4[i]:_Status_index_4[i+1]]
	case 165 <= i && i <= 169:
		i -= 165
		return _Status_name_5[_Status_index_5[i]:_Status_index_5[i+1]]
	case 193 <= i && i <= 196:
		i -= 193
		return _Status_name_6[_Status_index_6[i]:_Status_index_6[i+1]]
	case 198 <= i && i <= 208:
		i -= 198
		return _Status_name_7[_Status_index_7[i]:_Status_index_7[i+1]]
	case 230 <= i && i <= 242:
		i -= 230
		return _Status_name_8[_Status_index_8[i]:_Status_index_8[i+1]]
	default:
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}

const _LatencyReq_name = "NoLatencyFastBeaconsSlowBeacons"

var _LatencyReq_index = [...]uint8{0, 9, 20, 31}

func (i LatencyReq) String() string {
	if i >= LatencyReq(len(_LatencyReq_index)-1) {
		return "LatencyReq(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LatencyReq_name[_LatencyReq_index[i]:_LatencyReq_index[i+1]]
}

const _DeviceState_name = "InitializedNotStartedAutomaticallyInitializedNotConnectedToAnythingDiscoveringPANsToJoinJoiningPANRejoiningPANJoinedButNotAuthenticatedStartedAsDeviceAfterAuthenticationDeviceJoinedAuthenticatedAndIsRouterStartingAsZigBeeCoordinatorStartedAsZigBeeCoordinatorDeviceHasLostInformationAboutItsParent"

var _DeviceState_index = [...]uint16{0, 34, 67, 88, 98, 110, 135, 169, 205, 232, 258, 296}

func (i DeviceState) String() string {
	if i >= DeviceState(len(_DeviceState_index)-1) {
		return "DeviceState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceState_name[_DeviceState_index[i]:_DeviceState_index[i+1]]
}
