// Code generated by "stringer -type Status,LatencyReq,DeviceState -output const_strings.go"; DO NOT EDIT.

package znp

import "strconv"

const _LatencyReq_name = "NoLatencyFastBeaconsSlowBeacons"

var _LatencyReq_index = [...]uint8{0, 9, 20, 31}

func (i LatencyReq) String() string {
	if i >= LatencyReq(len(_LatencyReq_index)-1) {
		return "LatencyReq(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LatencyReq_name[_LatencyReq_index[i]:_LatencyReq_index[i+1]]
}

const _StartupFromAppStatus_name = "RestoredNetworkStateNewNetworkStateLeaveAndNotStarted"

var _StartupFromAppStatus_index = [...]uint8{0, 20, 35, 53}

func (i StartupFromAppStatus) String() string {
	if i >= StartupFromAppStatus(len(_StartupFromAppStatus_index)-1) {
		return "StartupFromAppStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StartupFromAppStatus_name[_StartupFromAppStatus_index[i]:_StartupFromAppStatus_index[i+1]]
}

const _Status_name = "SuccessFailureInvalidParameterItemCreatedAndInitializedInitializationFailedBadLengthMemErrorBufferFullUnsupportedModeMacMemErrorSapiInProgressSapiTimeoutSapiInitNotAuthorizedMalformedCmdUnsupClusterCmdZdpInvalidEpZdpNotActiveZdpNotSupportedZdpTimeoutZdpNoMatchZdpNoEntryZdpNoDescriptorZdpInsufficientSpaceZdpNotPermittedZdpTableFullZdpNotAuthorizedZdpBindingTableFullOtaAbortOtaImageInvalidOtaWaitForDataOtaNoImageAvailableOtaRequireMoreImageSecNoKeySecOldFrmCountSecMaxFrmCountSecCcmFailSecFailureApsFailApsTableFullApsIllegalRequestApsInvalidBindingApsUnsupportedAttribApsNotSupportedApsNoAckApsDuplicateEntryApsNoBoundDeviceApsNotAllowedApsNotAuthenticatedNwkInvalidParamNwkInvalidRequestNwkNotPermittedNwkStartupFailureNwkAlreadyPresentNwkSyncFailureNwkTableFullNwkUnknownDeviceNwkUnsupportedAttributeNwkNoNetworksNwkLeaveUnconfirmedNwkNoAckNwkNoRouteMacBeaconLossMacChannelAccessFailureMacDeniedMacDisableTrxFailureMacFailedSecurityCheckMacFrameTooLongMacInvalidGTSMacInvalidHandleMacInvalidParameterMacNoACKMacNoBeaconMacNoDataMacNoShortAddrMacOutOfCapMacPANIDConflictMacRealignmentMacTransactionExpiredMacTransactionOverFlowMacTxActiveMacUnAvailableKeyMacUnsupportedAttributeMacUnsupportedMacSrcMatchInvalidIndex"

var _Status_map = map[Status]string{
	0:   _Status_name[0:7],
	1:   _Status_name[7:14],
	2:   _Status_name[14:30],
	9:   _Status_name[30:55],
	10:  _Status_name[55:75],
	12:  _Status_name[75:84],
	16:  _Status_name[84:92],
	17:  _Status_name[92:102],
	18:  _Status_name[102:117],
	19:  _Status_name[117:128],
	32:  _Status_name[128:142],
	33:  _Status_name[142:153],
	34:  _Status_name[153:161],
	126: _Status_name[161:174],
	128: _Status_name[174:186],
	129: _Status_name[186:201],
	130: _Status_name[201:213],
	131: _Status_name[213:225],
	132: _Status_name[225:240],
	133: _Status_name[240:250],
	134: _Status_name[250:260],
	136: _Status_name[260:270],
	137: _Status_name[270:285],
	138: _Status_name[285:305],
	139: _Status_name[305:320],
	140: _Status_name[320:332],
	141: _Status_name[332:348],
	142: _Status_name[348:367],
	149: _Status_name[367:375],
	150: _Status_name[375:390],
	151: _Status_name[390:404],
	152: _Status_name[404:423],
	153: _Status_name[423:442],
	161: _Status_name[442:450],
	162: _Status_name[450:464],
	163: _Status_name[464:478],
	164: _Status_name[478:488],
	173: _Status_name[488:498],
	177: _Status_name[498:505],
	178: _Status_name[505:517],
	179: _Status_name[517:534],
	180: _Status_name[534:551],
	181: _Status_name[551:571],
	182: _Status_name[571:586],
	183: _Status_name[586:594],
	184: _Status_name[594:611],
	185: _Status_name[611:627],
	186: _Status_name[627:640],
	187: _Status_name[640:659],
	193: _Status_name[659:674],
	194: _Status_name[674:691],
	195: _Status_name[691:706],
	196: _Status_name[706:723],
	197: _Status_name[723:740],
	198: _Status_name[740:754],
	199: _Status_name[754:766],
	200: _Status_name[766:782],
	201: _Status_name[782:805],
	202: _Status_name[805:818],
	203: _Status_name[818:837],
	204: _Status_name[837:845],
	205: _Status_name[845:855],
	224: _Status_name[855:868],
	225: _Status_name[868:891],
	226: _Status_name[891:900],
	227: _Status_name[900:920],
	228: _Status_name[920:942],
	229: _Status_name[942:957],
	230: _Status_name[957:970],
	231: _Status_name[970:986],
	232: _Status_name[986:1005],
	233: _Status_name[1005:1013],
	234: _Status_name[1013:1024],
	235: _Status_name[1024:1033],
	236: _Status_name[1033:1047],
	237: _Status_name[1047:1058],
	238: _Status_name[1058:1074],
	239: _Status_name[1074:1088],
	240: _Status_name[1088:1109],
	241: _Status_name[1109:1131],
	242: _Status_name[1131:1142],
	243: _Status_name[1142:1159],
	244: _Status_name[1159:1182],
	245: _Status_name[1182:1196],
	255: _Status_name[1196:1219],
}

func (i Status) String() string {
	if str, ok := _Status_map[i]; ok {
		return str
	}
	return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
}

const (
	_AddrMode_name_0 = "AddrNotPresentAddrGroupAddr16BitAddr64Bit"
	_AddrMode_name_1 = "AddrBroadcast"
)

var (
	_AddrMode_index_0 = [...]uint8{0, 14, 23, 32, 41}
)

func (i AddrMode) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _AddrMode_name_0[_AddrMode_index_0[i]:_AddrMode_index_0[i+1]]
	case i == 15:
		return _AddrMode_name_1
	default:
		return "AddrMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}

const _InterPanCommand_name = "InterPanClrInterPanSetInterPanRegInterPanChk"

var _InterPanCommand_index = [...]uint8{0, 11, 22, 33, 44}

func (i InterPanCommand) String() string {
	if i >= InterPanCommand(len(_InterPanCommand_index)-1) {
		return "InterPanCommand(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InterPanCommand_name[_InterPanCommand_index[i]:_InterPanCommand_index[i+1]]
}

const (
	_Channel_name_0 = "AIN0AIN1AIN2AIN3AIN4AIN5AIN6AIN7"
	_Channel_name_1 = "TemperatureSensorVoltageReading"
)

var (
	_Channel_index_0 = [...]uint8{0, 4, 8, 12, 16, 20, 24, 28, 32}
	_Channel_index_1 = [...]uint8{0, 17, 31}
)

func (i Channel) String() string {
	switch {
	case 0 <= i && i <= 7:
		return _Channel_name_0[_Channel_index_0[i]:_Channel_index_0[i+1]]
	case 22 <= i && i <= 23:
		i -= 22
		return _Channel_name_1[_Channel_index_1[i]:_Channel_index_1[i+1]]
	default:
		return "Channel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}

const _Resolution_name = "Bit8Bit10Bit12Bit14"

var _Resolution_index = [...]uint8{0, 4, 9, 14, 19}

func (i Resolution) String() string {
	if i >= Resolution(len(_Resolution_index)-1) {
		return "Resolution(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Resolution_name[_Resolution_index[i]:_Resolution_index[i+1]]
}

const _Operation_name = "SetDirectionSetInputModeSetClearToggleRead"

var _Operation_index = [...]uint8{0, 12, 24, 27, 32, 38, 42}

func (i Operation) String() string {
	if i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}

const _Reason_name = "PowerUpExternalWatchDog"

var _Reason_index = [...]uint8{0, 7, 15, 23}

func (i Reason) String() string {
	if i >= Reason(len(_Reason_index)-1) {
		return "Reason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Reason_name[_Reason_index[i]:_Reason_index[i+1]]
}

const _DeviceState_name = "InitializedNotStartedAutomaticallyInitializedNotConnectedToAnythingDiscoveringPANsToJoinJoiningPANRejoiningPANJoinedButNotAuthenticatedStartedAsDeviceAfterAuthenticationDeviceJoinedAuthenticatedAndIsRouterStartingAsZigBeeCoordinatorStartedAsZigBeeCoordinatorDeviceHasLostInformationAboutItsParent"

var _DeviceState_index = [...]uint16{0, 34, 67, 88, 98, 110, 135, 169, 205, 232, 258, 296}

func (i DeviceState) String() string {
	if i >= DeviceState(len(_DeviceState_index)-1) {
		return "DeviceState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceState_name[_DeviceState_index[i]:_DeviceState_index[i+1]]
}

const (
	_SubsystemId_name_0 = "Sys"
	_SubsystemId_name_1 = "Mac"
	_SubsystemId_name_2 = "Nwk"
	_SubsystemId_name_3 = "Af"
	_SubsystemId_name_4 = "Zdo"
	_SubsystemId_name_5 = "Sapi"
	_SubsystemId_name_6 = "Util"
	_SubsystemId_name_7 = "Debug"
	_SubsystemId_name_8 = "App"
	_SubsystemId_name_9 = "AllSubsystems"
)

func (i SubsystemId) String() string {
	switch {
	case i == 256:
		return _SubsystemId_name_0
	case i == 512:
		return _SubsystemId_name_1
	case i == 768:
		return _SubsystemId_name_2
	case i == 1024:
		return _SubsystemId_name_3
	case i == 1280:
		return _SubsystemId_name_4
	case i == 1536:
		return _SubsystemId_name_5
	case i == 1792:
		return _SubsystemId_name_6
	case i == 2048:
		return _SubsystemId_name_7
	case i == 2304:
		return _SubsystemId_name_8
	case i == 65535:
		return _SubsystemId_name_9
	default:
		return "SubsystemId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}

const _Action_name = "DisableEnable"

var _Action_index = [...]uint8{0, 7, 13}

func (i Action) String() string {
	if i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}

const _Shift_name = "NoShiftYesShift"

var _Shift_index = [...]uint8{0, 7, 15}

func (i Shift) String() string {
	if i >= Shift(len(_Shift_index)-1) {
		return "Shift(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Shift_name[_Shift_index[i]:_Shift_index[i+1]]
}

const _Mode_name = "OFFON"

var _Mode_index = [...]uint8{0, 3, 5}

func (i Mode) String() string {
	if i >= Mode(len(_Mode_index)-1) {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}

const _Relation_name = "ParentChildRfdChildRfdRxIdleChildFfdChildFfdRxIdleNeighborOther"

var _Relation_index = [...]uint8{0, 6, 14, 28, 36, 50, 58, 63}

func (i Relation) String() string {
	if i >= Relation(len(_Relation_index)-1) {
		return "Relation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Relation_name[_Relation_index[i]:_Relation_index[i+1]]
}

const _ReqType_name = "SingleDeviceResponseAssociatedDevicesResponse"

var _ReqType_index = [...]uint8{0, 20, 45}

func (i ReqType) String() string {
	if i >= ReqType(len(_ReqType_index)-1) {
		return "ReqType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReqType_name[_ReqType_index[i]:_ReqType_index[i+1]]
}
